[workspace]
resolver = "3"
members = ["admin-server","client-server", "furniture"]


[profile.dev.package.sqlx-macros]
opt-level = 3

[profile.release]
opt-level = 3           # Maximum speed optimizations (use 'z' or 's' if binary size is your priority)
lto = true              # Enables Link-Time Optimization across all dependency crates
codegen-units = 1       # Reduces parallel compilation units to allow deeper global optimizations
panic = "abort"         # Removes panic unwinding infrastructure to reduce binary size and overhead
strip = true            # Automatically strips debug symbols from the final binary