[package]
name = "my-home-admin-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
tokio = { version = "1.52.3", features = ["full"] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite", "macros"] }
anyhow = "1.0.104"
tower-http = { version = "0.7.0", features = ["cors", "validate-request"] }
furniture = {path = "../furniture"}
dotenvy = "0.15.7"
